spring.application.name=Car Rental

# ==========================================
# 1. 資料庫連線設定 (優先讀取環境變數，若無則使用預設值)
# ==========================================
# 資料庫連線 URL (預設連至 AWS RDS，資料庫名稱改為與 Terraform 一致的 carrental)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/myjdbc?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true&characterEncoding=UTF-8}

# MySQL 的帳號與密碼 (從環境變數讀取)
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:springboot}

# MySQL 驅動程式
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jackson.time-zone=GMT+8
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# ==========================================
# 2. JPA / Hibernate 設定
# ==========================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 自動建立/更新資料表結構策略
# update: 依據 Entity 自動建立或更新 Table 欄位 (開發階段推薦)
# validate / none: 如果資料庫內已有現成表格，且不想讓 JPA 改變結構，請設為 none
spring.jpa.hibernate.ddl-auto=update
# 告訴 Spring Boot 啟動時要執行 data.sql 匯入初始資料
spring.sql.init.mode=always

# 指定 SQL 方言
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 確保 JPA 實體會在 Flyway 完成 Table 建立後才初始化
spring.jpa.defer-datasource-initialization=true


# ==========================================
# 4. Swagger / OpenAPI 文件設定
# ==========================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html